### ISSUE TITLE
Unexpected behavior: If .fault file has no header line 

### ISSUE THREAD

**Issue by dmelgarm** [dmelgarm/MudPy#12]
The code runs normally but the GF computation is out of order and it leads to strange looking inversions because the GFs are out of order and don;t correpsond tot he correct subfault numbers. The solution is to ALWAYS ensure .fault file has a siongle header line OR for me to not be lazy and actually look at where this error is introduced and do a little re-writting. This is probably in green.py

**Comment by tututingting** [comment]
Has this bug been fixed? I used this program to do inversion of nepal earthquake provided by the examples. I have tried many times, but the result was terrible. I have read and checked all the issues list here, except this one. Because if I add a single header line in the .fault file, the program will report errors. I do not know how to get the correct GF. Could you give a detail of the solution?

**Comment by dmelgarm** [comment]
Fixed.
